### ISSUE TITLE
add a button to "select all" choices in dashboard dropdowns

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/discord-bot#441]
### Describe the Feature

![image](https://user-images.githubusercontent.com/5033303/233707416-aa6d4043-2c71-48eb-a028-786e9da0968a.png)

**Comment by loki1205** [comment]
Hi, I would love to work on this one. Can you plz assign this to me?

**Comment by josefaidt** [comment]
Hey @loki1205 :wave: apologies I did not see this comment before merging the PR for this! This is now closed with https://github.com/aws-amplify/discord-bot/pull/443, but I'd be happy to walk through other good first issues we have!
